name       : gifsicle
version    : '1.91'
release    : 2
source     :
    - https://www.lcdf.org/gifsicle/gifsicle-1.91.tar.gz : 0a4ee602aa244cdcdd86a250a6b39c94d8343cf526b8fae862d8a0efc337a800
license    : GPL-2.0
component  : multimedia.graphics
summary    : Gifsicle manipulates GIF image files.
description: |
    Gifsicle manipulates GIF image files. Depending on command line options, it can merge several GIFs into a GIF animation; explode an animation into its component frames; change individual frames in an animation; turn interlacing on and off; add transparency; add delays, disposals, and looping to animations; add and remove comments; flip and rotate; optimize animations for space; change images' colormaps; and other things.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
