name       : gifsicle
version    : 1.88
release    : 1
source     :
    - https://www.lcdf.org/gifsicle/gifsicle-1.88.tar.gz : 4585d2e683d7f68eb8fcb15504732d71d7ede48ab5963e61915201f9e68305be
license    : GPL-2.0
component  : multimedia.graphics
summary    : Gifsicle manipulates GIF image files.
description: |
    Gifsicle manipulates GIF image files. Depending on command line options, it can merge several GIFs into a GIF animation; explode an animation into its component frames; change individual frames in an animation; turn interlacing on and off; add transparency; add delays, disposals, and looping to animations; add and remove comments; flip and rotate; optimize animations for space; change images' colormaps; and other things.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
